### PR TITLE
CSCMETAX-196: Make preferred_identifier unique within a data catalog

### PR DESCRIPTION
**Pull request by hannu40k**

### CODE REVIEW

**Comment by hannu40k** [comment]
Actually retrieving by preferred_identifier is broken now when there are alternate records, since django does not know how to handle returning multiple objects from /resource/id...

**Comment by junsk1** [comment]
I'm assuming the relevant code here does not get run on DELETE operations? If it does, has it been tested as well?

**Comment by junsk1** [comment]
Also, not exactly related to this ticket, but: Has it been considered how this paradigm change will affect rest of the APIs. I'm thinkinf of exists API. Should it be extended to optionally include data catalog id to ask metax whether a dataset exists only in a specific data catalog

**Comment by hannu40k** [comment]
Update / delete operations only search by urn_identifier, so a DELETE with a preferred_identifier which would accidentally delete multiple records is not possible.

As for the exists API, instead of returning a simple true/false, the API could return the type of the identifier found, and the catalog identifier it belongs to. Then again, at that point it would be almost the same to just return the whole object.

**Pull request closed without merging**
